In [1]:
import numpy as np 

In [2]:
arr1 = np.array([1,2,3,4])


In [3]:
arr1.shape

(4,)

In [6]:
arr1.dtype


dtype('int32')

In [8]:
arr1.ndim

1

In [9]:
arr1 = np.array([1,2,3,4], dtype = np.float)


C:\Users\Stephen\AppData\Local\Temp/ipykernel_28908/4291707370.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1 = np.array([1,2,3,4], dtype = np.float)


In [11]:
arr1.dtype


dtype('float64')

In [13]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr3 = np.arange(0,100,5)
arr3

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [22]:
arr_rand = np.random.randint(1,100)
arr_rand

73

In [23]:
arr_sqrt = np.sqrt(arr2)
arr_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [25]:
arr1 = np.arange(10,20)
arr1 


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
arr1 + arr2 

ValueError: operands could not be broadcast together with shapes (4,) (10,) 

In [26]:
arr1*arr2 

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [27]:
arr2**2 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [30]:
arr2.min()
arr2.max()
arr2.std()

2.8722813232690143

In [31]:
arr1 > 14

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [42]:
arr4 = np.arange(1,100,5)

arr4

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [43]:
arr4.ndim

1

In [35]:
arr4.dtype

dtype('int32')

In [36]:
arr4.shape

(20,)

In [37]:
arr4.std()

28.83140648667699

In [41]:
arr4_sqrt = np.sqrt(arr4.std())
arr4_sqrt

5.3694884753277

In [45]:
arr1


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
np.insert(arr1, 5, 10)

array([10, 11, 12, 13, 14, 10, 15, 16, 17, 18, 19])

In [48]:
arr5 = np.array([1,20,5,123,1234])

In [49]:
arr5.sort()

In [53]:
arr5 = np.counstenate(arr1,arr2)

AttributeError: module 'numpy' has no attribute 'counstenate'

In [54]:
arr5[(arr5 + 4)]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [56]:
matr1 = np.array([(1,2,3),(2,3,4),(5,6,7)])
matr1

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [58]:
matr1.ndim

2

In [59]:
matr1.shape

(3, 3)

In [60]:
matr1.size

9

In [64]:
matr1.reshape(9,1)

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [66]:
matr2 = np.array([(1,2,3),(8,7,6),(12,13,14),(15,31,90)])
matr2 
matr3 = np.array([(5,123,43),(19,0,19),(1,3,70),(12,10,9)])
matr3 




array([[  5, 123,  43],
       [ 19,   0,  19],
       [  1,   3,  70],
       [ 12,  10,   9]])

In [72]:
matr4 =  matr2 + matr3

In [68]:
matr2[:,1]

array([ 2,  7, 13, 31])

In [73]:
matr4[matr4 > 5] 

array([  6, 125,  46,  27,   7,  25,  13,  16,  84,  27,  41,  99])